empty PR

diff --git a/.github/workflows/pr_metadata_check.yml b/.github/workflows/pr_metadata_check.yml
--- a/.github/workflows/pr_metadata_check.yml
+++ b/.github/workflows/pr_metadata_check.yml
@@ -26,9 +26,11 @@ jobs:
           exit 1
 
   empty_pr_description:
-    - name: Check for PR description
-      if: ${{ github.event.pull_request.body == '' }}
-      id: pr_description
-      run: |
-        echo "Pull request description cannot be empty."
-        exit 1
+    if: ${{ github.event.pull_request.body == '' }}
+    name: PR Description
+    runs-on: ubuntu-22.04
+    steps:
+      - name: Check for PR description
+        run: |
+          echo "Pull request description cannot be empty."
+          exit 1
